### ISSUE TITLE
Add support for multi type constraints

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/im-tables#34] opened 2013-03-24 01:57 UTC
A test query is needed.

**Comment by Manasa2850** [comment] 2020-03-19 16:12
@yochannah I would like to work on this. 
Could you please let me know what exactly the issue is?

**Comment by yochannah** [comment] 2020-03-19 16:29
@Manasa2850 - I'll be honest, the issue is pretty sparse and I don't know what the aim of the game was here! 😆  let's close this one - the person who created the issue hasn't worked at InterMine for a while.

**Closed by yochannah** 2020-03-19 16:29 UTC
Labels: enhancement
