### ISSUE TITLE
update stylesheet to work nicely with very short screens

### ISSUE THREAD

**Issue by yochannah** [intermine/im-tables#164] opened 2018-08-22 09:19 UTC
see https://github.com/intermine/intermine/issues/1658#issuecomment-414805564 - this bug only happens in the sandbox mode stylesheet, not standalone. 

Suggest we just add the relevant styles to the less and make a small point release.

**Comment by firshta2016** [comment] 2020-03-11 18:46
Hi @yochannah I am an Outreachy applicant, would like to work on this issue.

**Comment by firshta2016** [comment] 2020-03-11 19:55
@yochannah could you please explain what the issue is when the screen gets smaller? I did some tests I found that when the screen gets smalls the buttons on the top losses half of its 'content' or 'words' see screen attached- for example: instead of saying 'generate python code' it only says 'python'. Is this what you are talking about or would this be a different issue? 

Also, I read your suggestion to add the relevant styles from issue#1658 but looking over the LESS files I wasnt sure where you would add the code you suggested, maybe in modals.less or tables.less..? thank you for your help in advance. 

![image](https://user-images.githubusercontent.com/24639588/76458424-c7b59880-6397-11ea-80d0-773cf30c7a53.png)

**Comment by yochannah** [comment] 2020-03-12 16:42
Hey @firshta2016! Feel free to pick this up. 

>  I did some tests I found that when the screen gets smalls the buttons on the top losses half of its 'content' or 'words' see screen attached- for example: instead of saying 'generate python code' it only says 'python'. Is this what you are talking about or would this be a different issue?

that's something different :) If I recall correctly, if you press the manage columns button, you should get something like this (below), but with the bottom of the modal buttons cut off. You might need to test it out on a live intermine or make sure you're using the sandboxed css file, not the normal one. modals.less sounds like a good place to put this! 

![image](https://user-images.githubusercontent.com/9271438/76544639-4ab21e00-6480-11ea-853f-20c9302828a7.png)

**Comment by firshta2016** [comment] 2020-03-12 17:32
is this what you mean? where the bottom buttons are cut of when the screen gets shorter?
![image](https://user-images.githubusercontent.com/24639588/76548952-c8f4cd00-644c-11ea-89f2-ddd81471ef25.png)

**Comment by yochannah** [comment] 2020-03-12 17:51
that is it! ⭐️

**Comment by firshta2016** [comment] 2020-03-12 21:03
@yochannah after testing out multiple ways, I came up with this: please see attached image and if you approve how it looks I can go ahead and create a PR. 

I made the modal scrollable so when the screen size gets short, you have the option of scrolling down instead of it being completely cut off. :)

![image](https://user-images.githubusercontent.com/24639588/76566310-b63cc100-6469-11ea-948a-f07d8a4cd23b.png)

**Comment by yochannah** [comment] 2020-03-13 15:24
that looks perfect! Please PR it <3

**Comment by heralden** [comment] 2020-12-01 12:49
Fixed with #216

**Closed by heralden** 2020-12-01 12:49 UTC
